platform :ios, "8.0"
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'

pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'JSBadgeView'
pod 'SDWebImage'
pod 'DateTools'
pod 'LoremIpsum'
pod 'VBFPopFlatButton'
pod 'MBProgressHUD'
pod 'ActionSheetPicker-3.0'
pod 'INTULocationManager'
pod 'GoogleMaps'
pod 'LMGeocoder'
pod 'SLPagingView'
pod 'EZSwipeController'
pod 'XLPagerTabStrip', '~> 3.0'
pod 'BFPaperButton'
pod 'PureLayout'
pod 'MGSwipeTableCell'
pod 'SlackTextViewController'
pod 'KMPlaceholderTextView'
pod 'CCBottomRefreshControl'
pod 'Colours'
pod 'MXParallaxHeader'
pod 'JDStatusBarNotification'
pod 'DGActivityIndicatorView'
pod 'TLTagsControl', :git => 'https://github.com/ali312/TLTagsControl'
pod 'NYTPhotoViewer', '~> 1.1.0'
pod 'Obfuscator'
pod 'RNCryptor', '~> 4.0.0-beta'
pod 'JSQMessagesViewController'
pod 'SVPullToRefresh', :git => 'https://github.com/gabro/SVPullToRefresh.git', :branch => 'top-infinitescrolling'
pod 'EFCircularSlider'
pod 'CircleProgressBar'
pod 'LGPlusButtonsView', '~> 1.1.0'
pod 'SocketRocket'
pod 'TOCropViewController'
pod 'VWWPermissionKit'
pod 'TLYShyNavBar'
pod 'Siren'
pod 'TTTAttributedLabel'
